### PR TITLE
ALT+W to close the document, not quit

### PR DESCRIPTION
**Pull request by humdingerb**

### CODE REVIEW

**Comment by humdingerb** [comment]
BTW, don't feel any pressure with me opening up all those issues. I just document possible enhancements and bugs that you're totally free to agree/reject/postpone in your own time, of course. :)

**Comment by threedeyes** [comment]
MSG_FILE_CLOSE - (File-> Close) - closes the file, but not the window
Alt + W - close the file window
These are different actions

**Comment by threedeyes** [comment]
> BTW, don't feel any pressure with me opening up all those issues. I just document possible enhancements and bugs that you're totally free to agree/reject/postpone in your own time, of course. :)

Everything is fine. Feedback is important.

**Comment by humdingerb** [comment]
> MSG_FILE_CLOSE - (File-> Close) - closes the file, but not the window
Alt + W - close the file window
These are different actions

This is one way to look at it.
The issue here becomes that STLover provides an "empty" window - contrary to most Haiku apps. This is nice when starting the app without double-clicking a document. I'm not sure I see the need to get back to that "welcome view" when closing the current document. In fact, I don't see the need for the "Close" (document) menu item at all:
If you want to open another doc in the same window, use ALT+O.
If you have the new document in some open Tracker window, ready to be drag&dropped on the empty STLover window, just double-click it instead. STLover is a small app, so re-launching takes the blink of an eye...

Anyway, you're correct to reject this PR. But maybe think about if the "Close" item is actually needed at all.

**Pull request closed without merging**
